[functions]
external_node_modules = ["vscode-oniguruma","shiki"]
node_bundler = "esbuild"
[build]
environment = { NODE_VERSION = "20.4.0" }
command = "pnpm --filter stats run build"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF sites/main-site/src/components sites/main-site/src/layouts sites/stats" # don't build if there are no changes
[[headers]]
for = "/_astro/*"
[headers.values]
Access-Control-Allow-Origin = "*"
