[functions]
external_node_modules = ["vscode-oniguruma","shiki"]
node_bundler = "esbuild"
[build]
environment = { NODE_VERSION = "20.4.0" }
command = "pnpm --filter main-site run build"
[images]
remote_images = ["https://raw.githubusercontent.com/.*", "https://images.unsplash.com/.*"]
[[headers]]
for = "/_astro/*"
[headers.values]
Access-Control-Allow-Origin = "*"
